export const elements = {
    displays: {}, progressModalCloseBtn: null, exchangeModalCloseBtn: null, exchangeModalBody: null, dungeon5pList: null, dungeon10pList: null, dungeon25pList: null, characterBtn: null, characterModal: null, characterModalCloseBtn: null, charGearScoreDisplay: null, charProficiencyDisplay: null, charGoldDisplay: null, charAbyssCrystalDisplay: null, charHeroismDisplay: null, charValorDisplay: null, charConquestDisplay: null, charTriumphDisplay: null, charFrostDisplay: null, charAtiyehsuideDisplay: null, charWalanaiersuideDisplay: null, charLushichuanshuodesuideDisplay: null, charYingzhisuideDisplay: null, charShuangzhisuideDisplay: null, itemTooltip: null, characterModalBody: null, collectiblesBtn: null, collectiblesModal: null, collectiblesModalCloseBtn: null, collectiblesModalBody: null, settingsBtn: null, settingsModal: null, settingsModalCloseBtn: null, helpModal: null, gameHelpBtn: null, helpModalCloseBtn: null, clearSaveBtn: null, exportSaveBtn: null, importSaveBtn: null, ascendBtn: null, reminderContainer: null, specialItemsContainer: null, lootPopup: null, messageContainer: null, questList: null, dungeon5Btn: null, dungeon10Btn: null, dungeon25Btn: null, viewProgressBtn: null, progressModal: null, exchangeBtn: null, exchangeModal: null, sceneIndicator: null, dungeonProgressTitle: null, bossList: null,
    chestBtn: null, chestBadge: null
};
export function initElements() {
    const el = elements; const doc = document; const get = (id) => doc.getElementById(id);
    el.messageContainer = get('messageContainer'); el.questList = get('questList'); el.dungeon5Btn = get('dungeon5Btn'); el.dungeon10Btn = get('dungeon10Btn'); el.dungeon25Btn = get('dungeon25Btn'); el.viewProgressBtn = get('viewProgressBtn'); el.progressModal = get('progressModal'); el.exchangeBtn = get('exchangeBtn'); el.exchangeModal = get('exchangeModal'); el.sceneIndicator = get('sceneIndicator');
    el.displays.gearScore = get('gearScoreDisplay'); el.displays.gold = get('goldDisplay'); el.displays.proficiency = get('proficiencyDisplay'); el.specialItemsContainer = get('specialItemsContainer'); el.dungeonProgressTitle = get('dungeonProgressTitle'); el.bossList = get('bossList'); el.characterBtn = get('characterBtn'); el.characterModal = get('characterModal'); el.collectiblesBtn = get('collectiblesBtn'); el.collectiblesModal = get('collectiblesModal'); el.itemTooltip = get('itemTooltip'); el.reminderContainer = get('reminderContainer'); el.lootPopup = get('lootPopup');
    el.settingsBtn = get('settingsBtn'); el.settingsModal = get('settingsModal'); el.settingsModalCloseBtn = get('settingsModalCloseBtn'); el.helpModal = get('helpModal'); el.gameHelpBtn = get('gameHelpBtn'); el.helpModalCloseBtn = get('helpModalCloseBtn'); el.clearSaveBtn = get('clearSaveBtn'); el.exportSaveBtn = get('exportSaveBtn'); el.importSaveBtn = get('importSaveBtn'); el.ascendBtn = get('ascendBtn');
    el.collectiblesModalCloseBtn = get('collectiblesModalCloseBtn'); el.collectiblesModalBody = get('collectiblesModalBody'); el.characterModalCloseBtn = get('characterModalCloseBtn'); el.characterModalBody = doc.querySelector('#characterModal .character-detailed-layout'); el.progressModalCloseBtn = get('progressModalCloseBtn'); el.dungeon5pList = get('dungeon5pList'); el.dungeon10pList = get('dungeon10pList'); el.dungeon25pList = get('dungeon25pList'); el.exchangeModalCloseBtn = get('exchangeModalCloseBtn'); el.exchangeModalBody = get('exchangeModalBody');
    el.charGearScoreDisplay = get('charGearScoreDisplay'); el.charProficiencyDisplay = get('charProficiencyDisplay'); el.charGoldDisplay = get('charGoldDisplay'); el.charAbyssCrystalDisplay = get('charAbyssCrystalDisplay'); el.charHeroismDisplay = get('charHeroismDisplay'); el.charValorDisplay = get('charValorDisplay'); el.charConquestDisplay = get('charConquestDisplay'); el.charTriumphDisplay = get('charTriumphDisplay'); el.charFrostDisplay = get('charFrostDisplay'); el.charAtiyehsuideDisplay = get('charAtiyehsuideDisplay'); el.charWalanaiersuideDisplay = get('charWalanaiersuideDisplay'); el.charLushichuanshuodesuideDisplay = get('charLushichuanshuodesuideDisplay'); el.charYingzhisuideDisplay = get('charYingzhisuideDisplay'); el.charShuangzhisuideDisplay = get('charShuangzhisuideDisplay');
    el.chestBtn = get('chestBtn'); el.chestBadge = get('chestBadge');
}